#!/bin/bash
set -x

aws datapipeline put-pipeline-definition --pipeline-definition file://daap-data-pipeline-viewership-aggregator.json --parameter-values myDaysAggregate="2" myShellCmd="sudo yum install -y perl-Switch perl-DateTime perl-Sys-Syslog perl-LWP-Protocol-https\ncurl http://aws-cloudwatch.s3.amazonaws.com/downloads/CloudWatchMonitoringScripts-1.2.1.zip -O\nunzip CloudWatchMonitoringScripts-1.2.1.zip\nrm CloudWatchMonitoringScripts-1.2.1.zip\ncp \${INPUT1_STAGING_DIR}/* .\nchmod u+x ./loop.sh\nchmod u+x ./run.sh\nchmod u+x ./viewership-aggregator\nchmod u+x ./precondition\n(crontab -l ; echo '*/1 * * * * ~/aws-scripts-mon/mon-put-instance-data.pl --mem-util --mem-used --mem-avail --disk-space-util --disk-path=/ --from-cron') | crontab -\n./loop.sh #{myDaysAggregate}\ncd aws-scripts-mon\n./mon-put-instance-data.pl --mem-util --mem-used --mem-avail\n" myS3InputLoc=s3://daap-pipeline/viewership-aggregator myS3OutputLoc=s3://daap-pipeline/ --pipeline-id df-10438742A3GXQZ7AJBNL

aws datapipeline put-pipeline-definition --pipeline-definition file://daap-data-pipeline-viewership-aggregator.json --parameter-values myDaysAggregate="3" myShellCmd="sudo yum install -y perl-Switch perl-DateTime perl-Sys-Syslog perl-LWP-Protocol-https\ncurl http://aws-cloudwatch.s3.amazonaws.com/downloads/CloudWatchMonitoringScripts-1.2.1.zip -O\nunzip CloudWatchMonitoringScripts-1.2.1.zip\nrm CloudWatchMonitoringScripts-1.2.1.zip\ncp \${INPUT1_STAGING_DIR}/* .\nchmod u+x ./loop.sh\nchmod u+x ./run.sh\nchmod u+x ./viewership-aggregator\nchmod u+x ./precondition\n(crontab -l ; echo '*/1 * * * * ~/aws-scripts-mon/mon-put-instance-data.pl --mem-util --mem-used --mem-avail --disk-space-util --disk-path=/ --from-cron') | crontab -\n./loop.sh #{myDaysAggregate}\ncd aws-scripts-mon\n./mon-put-instance-data.pl --mem-util --mem-used --mem-avail\n" myS3InputLoc=s3://daap-pipeline/viewership-aggregator myS3OutputLoc=s3://daap-pipeline/ --pipeline-id df-08452511PZ1B4F1NLXFK

aws datapipeline activate-pipeline --pipeline-id df-10438742A3GXQZ7AJBNL

aws datapipeline activate-pipeline --pipeline-id df-08452511PZ1B4F1NLXFK